- job-template:
    name: 'rest-test-runner'
    description: '<h3 style="color: green;">rest-test-runner</h3>'
    project-type: pipeline
    concurrent: false
    properties:
      - build-discarder:
          num-to-keep: 10
    parameters:
      - string:
          name: REFSPEC
          default: main
          description: Branch
      - string:
          name: base_url
          default: "https://petstore.swagger.io/v2/"
          description: tests base url
      - string:
          name: chat_id
          default: "-4970638051"
          description: Telegram chat for notification
      - string:
          name: bot_token
          default: ""
          description: Telegram bot token
    pipeline-scm:
      scm:
        - rest-test-runner
      script-path: ./Jenkinsfile
