- job-template:
    name: 'ui-test-runner'
    description: '<h3 style="color: green;">ui-test-runner</h3>'
    project-type: pipeline
    concurrent: false
    properties:
      - build-discarder:
          num-to-keep: 10
    parameters:
      - string:
          name: REFSPEC
          default: main
          description: Branch
      - text:
          name: YAML_CONFIG
          default: |
            browser: chrome
            base_url: https://otus.ru
            remote: true
            browser_version: 127.0
            enable_video: false
            enable_vnc: true
            selenoid_url: http://localhost/wd/hub
          description: config with properties
    pipeline-scm:
      scm:
        - ui-test-runner
      script-path: ./Jenkinsfile
