- job-template:
    name: 'wiremock-test-runner'
    description: '<h3 style="color: green;">wiremock-test-runner</h3>'
    project-type: pipeline
    concurrent: false
    properties:
      - build-discarder:
          num-to-keep: 10
    parameters:
      - string:
          name: REFSPEC
          default: main
          description: Branch
      - string:
          name: base_url
          default: "http://127.0.0.1"
          description: tests base url
    pipeline-scm:
      scm:
        - wiremock-test-runner
      script-path: ./Jenkinsfile
