---
- project:
    name: job-uploader
    jobs:
      - update-jobs


- project:
    name: ui-tests
    jobs:
      - ui-test-runner

- project:
    name: rest-tests
    jobs:
      - rest-test-runner

