---
- project:
    name: job-uploader
    jobs:
      - update-jobs


- project:
    name: ui-tests
    jobs:
      - ui-test-runner

- project:
    name: rest-tests
    jobs:
      - rest-test-runner

- project:
    name: wiremock-tests
    jobs:
      - wiremock-test-runner

- project:
    name: mobile-tests
    jobs:
      - mobile-test-runner

