---
- view:
    name: QA
    view-type: list
    description: |
      '<h2 style="color: green;">QA view</h2>'
    filter-executors: true
    filter-queue: true
    job-name:
      - 'update-jobs'
      - 'ui-test-runner'
#      - 'rest-test-runner'
      - 'mobile-test-runner'
      - 'wiremock-test-runner'
      - 'runner'
    columns:
      - status
      - weather
      - job
      - last-success
      - last-failure
      - last-duration
      - build-button