services:

  selenoid1:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid1
    hostname: selenoid1
    networks:
      - selenoid_net1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./grid-router/browsers.json:/etc/selenoid/browsers.json:ro  # Изменено
    command: -container-network selenoid_net1 -limit 10

  selenoid2:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid2
    hostname: selenoid2
    networks:
      - selenoid_net2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./grid-router/browsers.json:/etc/selenoid/browsers.json:ro  # Изменено
    command: -container-network selenoid_net2 -limit 10

  ggr:
    image: aerokube/ggr:1.7.2
    container_name: ggr
    hostname: ggr
    depends_on:
      - selenoid1
      - selenoid2
    volumes:
      - ./grid-router:/etc/grid-router:ro
    command: -guests-allowed -guests-quota "test" -verbose -quotaDir /etc/grid-router/quota
    networks:
      - selenoid_net1
      - selenoid_net2

  ggr-ui:
    image: aerokube/ggr-ui:1.2.0
    container_name: ggr-ui
    hostname: ggr_ui
    depends_on:
      - ggr
    volumes:
      - ./grid-router:/etc/grid-router:ro
    networks:
      - selenoid_net1
      - selenoid_net2

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid-ui
    hostname: selenoid-ui
    depends_on:
      - ggr-ui
    networks:
      - selenoid_net1
    command: --selenoid-uri http://ggr_ui:8888

  nginx:
    image: nginx:latest
    depends_on:
      - ggr
      - selenoid-ui
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - selenoid_net1

networks:
  selenoid_net1:
    name: selenoid_net1
  selenoid_net2:
    name: selenoid_net2