---
- scm:
    name: git-job-updater
    scm:
      - git:
          url: https://github.com/z1oyas/ansible_selenoid
          credentials-id: jenkins
          branches:
            - '${REFSPEC}'
          wipe-workspace: false
          prune: true